version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - '3306'
    env_file:
      - .env

  reference-release:
    container_name: prestashop_autoupgrade
    build:
      context: .
      dockerfile: ./.github/Dockerfile
      args:
        - VERSION=1.7.4.4
    volumes:
      - ./:/var/www/html/modules/autoupgrade
      - temp-ps:/var/www/html # Used for another container which needs .envPrestaShop content
    env_file:
      - .env
    ports:
      - '8001:80'

volumes:
  temp-ps:
