name: Nightly Upgrades
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  get_matrix:
    name: Set up matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - id: set-matrix
        run: echo "::set-output name=matrix::$(php ./.github/get_matrix.php)"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  upgrade:
    continue-on-error: true
    needs: get_matrix
    strategy:
      fail-fast: false
      matrix:
        from: ['1.7.6.9', '1.7.7.0', '1.6.1.24']
        ps-versions: ${{ fromJson(needs.get_matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    name: Upgrade
    outputs:
      result: ${{ steps.export-result.outputs.result }}
    steps:
      - uses: actions/checkout@v2
      - name: Composer Install
        run: |
          composer install
          echo "START_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`" >> $GITHUB_ENV
      - name: Upgrade & Rollback
        id: upgrade-rollback
        uses: ./.github/
      - name: Save result
        if: ${{ always() }}
        run: |
          export END_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
          echo "${{matrix.from}}|${{matrix.ps-versions.branch}}|${{matrix.ps-versions.version}}|$START_DATE|$END_DATE|${{steps.upgrade-rollback.outcome}}" > ${{matrix.from}}_${{matrix.ps-versions.branch}}.txt
      - name: Upload artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.from}}_${{matrix.ps-versions.branch}}
          path: ${{matrix.from}}_${{matrix.ps-versions.branch}}.txt
  results:
    name: Results
    continue-on-error: true
    runs-on: ubuntu-latest
    needs:
      - get_matrix
      - upgrade
    strategy:
      matrix:
        ps-versions: ${{ fromJson(needs.get_matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: ./artifacts/
      - name: Format results
        run: php ./.github/get_results.php ${{matrix.ps-versions.branch}}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GC_PROJECT_ID }}
          service_account_key: ${{ secrets.GC_SERVICE_KEY }}
          export_default_credentials: true
      - name: Push results to the nightly board
        run: |
          export FILENAME=autoupgrade_ui_`date -u +"%Y-%m-%d"`.json
          ./.github/workflows/nightly_scripts/push_results.sh ${{ env.nightly_api_url }} $FILENAME ${{ env.campaign }} ${{ env.platform }} ${{ secrets.QANB_TOKEN }}
        env:
          nightly_api_url: https://api-nightly.prestashop.com/hook/add
          campaign: autoupgrade
          platform: cli
